### ISSUE TITLE
Custom element doesn't exist: thermostat-card

### ISSUE THREAD

**Issue by totti4ever** [fineemb/lovelace-thermostat-card#4]
Installed via HACS, worked until the update yesterday. Webdev console says:

`GET http://ha/community_plugin/lovelace-thermostat-card/dist/styles.js?v=0.1.1 net::ERR_ABORTED 404 (Not Found)`

`GET http://ha/community_plugin/lovelace-thermostat-card/dist/thermostat_card.lib.js?v=0.1.1 net::ERR_ABORTED 404 (Not Found)`

`Uncaught (in promise) http://ha/community_plugin/lovelace-thermostat-card/main.js`

**Comment by peetereczek** [comment]
Also not working for me as I installed from HACS, same errors reported by web browser

**Comment by reaper7** [comment]
same for me

**Comment by fineemb** [comment]
Please update HACS to the latest version (0.21.5)
And reinstall lovelace-thermostat-card (v1.2.6)

The problem has been solved.

**Comment by peetereczek** [comment]
Sorry but not, HACS is not coping all the files from repository

![image](https://user-images.githubusercontent.com/42431204/74418066-14b15800-4e48-11ea-8096-eb04c2eea36d.png)

Error is still valid.

**Comment by totti4ever** [comment]
It is still a problem for me! If also for others I'll report a new issue

**Comment by xdenneboom** [comment]
these issues keep getting closed, but I have it now too, latest versions of everything, just installed. can't seem to get around the "card-type does not exist as many suggested above and multiple other issues.

**Comment by G8YTZ** [comment]
Same problem here, running the latest versions associated with 0.116.3. It does work after a fashion, but as soon as you add attributes like chevron-size or title the thermostat fails to load, either with a blank or red error message that the component does not exist. I used the config examples in the latest readme and di a reinstall of HACS and the component.

**Comment by Guenni75** [comment]
HACS install still not working.
Can't find the custom card.

**Comment by short-cheese-the-3rd** [comment]
I had this error and for me it was incorrect resource URL. For HACS users, it might need to be this instead of what is in the instructions:
- url: /**hacsfiles**/lovelace-thermostat-card/main.js
