### ISSUE TITLE
Thermostat presence error

### ISSUE THREAD

**Issue by peetereczek** [fineemb/lovelace-thermostat-card#5]
I have error:

```log
Uncaught TypeError: Cannot read property 'toLowerCase' of null
    at ThermostatUI._updateColor (thermostat_card.lib.js?v=0.1.1:332)
    at ThermostatUI.updateState (thermostat_card.lib.js?v=0.1.1:188)
    at HTMLElement.set hass [as hass] (main.js:42)
    at HTMLElement.value (hui-view.ts:61)
    at HTMLElement.value (hui-view.ts:337)
    at HTMLElement.t.addEventListener.once (hui-view.ts:68)
    at r (fire_event.ts:76)
    at create-element-base.ts:92
```
and that's true actually, as my thermostat preset_mode is null, when it's in manual mode

![image](https://user-images.githubusercontent.com/42431204/74376122-e00ab580-4de1-11ea-8314-64818582f6a0.png)

**Comment by fineemb** [comment]
Please update HACS to the latest version (0.21.5)
And reinstall lovelace-thermostat-card (v1.2.6)

The problem has been solved.

**Comment by peetereczek** [comment]
It's not fixed, still
Uncaught TypeError: Cannot read property 'toLowerCase' of null
    at ThermostatUI._updateColor (thermostat_card.lib.js?v=0.1.1:332)
    at ThermostatUI.updateState (thermostat_card.lib.js?v=0.1.1:188)
    at HTMLElement.set hass [as hass] (main.js:42)
    at HTMLElement.value (hui-view.ts:61)
    at HTMLElement.value (hui-view.ts:337)
    at HTMLElement.<anonymous> (hui-view.ts:68)
    at r (fire_event.ts:76)
    at create-element-base.ts:92
